# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.7.4"
Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/8.3.0"
  config.vm.hostname = "debian.kali"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network :private_network, type: :dhcp

  config.vm.provision :shell, privileged: true, path: "./scripts.sh"

  config.vm.provider :virtualbox do |vb|
    vb.name = "debian_kali"
    vb.memory = 4096
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.gui = true
  end

  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_update = true
    config.vbguest.no_remote = true
  end

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

end
